name: commons_dependencies
description: A new Flutter package project.
version: 0.0.1
author: Toshi Ossada
homepage: https://www.ioasys.com.br/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^3.1.1
  flutter_triple: ^1.0.5+1
  dio: ^4.0.0
  dartz: ^0.10.0-nullsafety.1
  asuka: ^2.0.0-nullsafety.2
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
